# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: server
    command: bash start.sh
  - name: shell
    init: git config pull.rebase false
    command: >

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - mhutchie.git-graph
